version: '3'

services:
  web:
    image: piapp/flask
    #build: ./pi_app
    hostname: flaskapp-server
    ports:
      - "5000:5000"
    volumes:
      - "./pi_app:/pi_app"
  nginx:
    image: nginx:alpine
    restart: always